require 'rake/clean'
require '../rake/gen_autoload'

TARGETS = [
    gen_autoload('src'),
    # gen_autoload('tests')
]

task default: TARGETS

desc 'Run tests'
task :test do
  # sh 'phpunit'
end

desc 'Install dependencies'
task :deps do
  # install dependencies here
end
